# Generated by Django 2.2.2 on 2019-08-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('ru', 'Russian')], max_length=20),
        ),
    ]
