# Generated by Django 2.2.2 on 2019-08-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190812_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en_us', 'English'), ('ru-ru', 'Russian')], max_length=20),
        ),
    ]
