# Generated by Django 2.2.2 on 2019-07-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
            ],
        ),
    ]
