# Generated by Django 2.2.3 on 2019-08-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='user_form',
            new_name='order',
        ),
    ]
