# Generated by Django 2.2.2 on 2019-08-22 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagetext',
            old_name='group',
            new_name='page',
        ),
    ]
