# Generated by Django 2.2.2 on 2019-09-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190910_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.SmallIntegerField(choices=[(0, '09-10'), (1, '10-11'), (2, '11-12'), (3, '12-13'), (4, '13-14'), (5, '14-15'), (6, '15-16'), (7, '16-17'), (8, '17-18'), (9, '18-18.30')], max_length=10, verbose_name='Delivery time'),
        ),
    ]
