# Generated by Django 2.2.2 on 2019-07-17 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orderitem_user_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user_input',
        ),
    ]
