# Generated by Django 2.2.2 on 2019-08-22 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190822_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('9-10', '9-10'), ('10-11', '10-11'), ('11-12', '11-12'), ('12-13', '12-13'), ('13-14', '13-14'), ('14-15', '14-15'), ('15-16', '15-16'), ('16-17', '16-17'), ('17-18', '17-18'), ('18-18.30', '18-18.30')], max_length=10, verbose_name='Delivery time'),
        ),
        migrations.AlterField(
            model_name='pagetext',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.PageTextGroup'),
        ),
        migrations.AlterField(
            model_name='pagetext',
            name='text',
            field=models.TextField(max_length=255),
        ),
    ]
