# Generated by Django 2.2.2 on 2019-08-22 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190822_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetextgroup',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagetext',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='shop.PageTextGroup'),
        ),
    ]
