# Generated by Django 2.2.2 on 2019-07-17 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_orderitem_user_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='user_input',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Order'),
            preserve_default=False,
        ),
    ]
