# Generated by Django 2.2.2 on 2019-08-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190822_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetext',
            name='text_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
