# Generated by Django 2.2.2 on 2019-07-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderitem_user_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='user_input',
            field=models.CharField(max_length=100),
        ),
    ]
