# Generated by Django 2.2.2 on 2019-08-30 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190829_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='pagetext',
            options={'verbose_name': 'Page text', 'verbose_name_plural': 'Page texts'},
        ),
        migrations.AlterModelOptions(
            name='pagetextgroup',
            options={'verbose_name': 'Page text', 'verbose_name_plural': 'Page texts'},
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Pizza', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('large', 'Large'), ('none', 'None')], max_length=100, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='pagetext',
            name='text',
            field=models.TextField(max_length=255, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='pagetext',
            name='text_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Text name'),
        ),
        migrations.AlterField(
            model_name='pagetextgroup',
            name='page_name',
            field=models.CharField(max_length=100, verbose_name='Page name'),
        ),
        migrations.AlterField(
            model_name='pagetextgroup',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
