# Generated by Django 2.2.2 on 2019-07-17 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190718_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='item_price',
        ),
    ]
