# Generated by Django 2.2.2 on 2019-07-18 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orderitem_user_input'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='user_input',
            new_name='user_form',
        ),
    ]
