# Generated by Django 2.2.2 on 2019-07-18 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_size'),
        ('shop', '0013_auto_20190718_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Pizza'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='user_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order'),
        ),
    ]
