# Generated by Django 2.2.2 on 2019-08-15 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('content', models.CharField(max_length=100, verbose_name='Content')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('category', models.ManyToManyField(to='catalog.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Pizzas',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('small', 'Small'), ('large', 'Large')], max_length=20, verbose_name='Type')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Price')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='catalog.Pizza', verbose_name='Pizza')),
            ],
        ),
    ]
