# Generated by Django 2.2.2 on 2019-08-14 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name_plural': 'Pizzas'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='category',
            field=models.ManyToManyField(to='catalog.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='content',
            field=models.CharField(max_length=100, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='photo',
            field=models.ImageField(upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='size',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='size',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='catalog.Pizza', verbose_name='Pizza'),
        ),
        migrations.AlterField(
            model_name='size',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='size',
            name='type',
            field=models.CharField(choices=[('small', 'Small'), ('large', 'Large')], max_length=20, verbose_name='Type'),
        ),
    ]
