# Generated by Django 2.2.2 on 2019-08-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'Pizza', 'verbose_name_plural': 'Pizzas'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
        migrations.AlterField(
            model_name='size',
            name='type',
            field=models.CharField(choices=[('small', 'Small'), ('large', 'Large'), ('none', 'None')], max_length=20, verbose_name='Type'),
        ),
    ]
