# Generated by Django 2.2.2 on 2019-07-18 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('small', 'Small'), ('large', 'Large')], max_length=20)),
                ('price', models.FloatField(default=0)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Pizza')),
            ],
        ),
    ]
