# Generated by Django 2.2.2 on 2019-07-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
