# Generated by Django 2.2.2 on 2019-07-18 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190719_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='price_large',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='price_small',
        ),
        migrations.AlterField(
            model_name='size',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='catalog.Pizza'),
        ),
    ]
