# Generated by Django 2.2.2 on 2019-07-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190719_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
