# Generated by Django 2.2.2 on 2019-07-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_size_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='type',
            field=models.CharField(choices=[('small', 'Small'), ('large', 'Large')], max_length=20),
        ),
    ]
