# Generated by Django 2.2.2 on 2019-07-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190720_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
