# Generated by Django 2.2.2 on 2019-08-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('weekday', models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('6', 'Saturday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('7', 'Sunday'), ('5', 'Friday')], max_length=1, verbose_name='Day of the week')),
                ('active', models.BooleanField(default=False, verbose_name='Working')),
                ('message', models.TextField(blank=True, max_length=225, null=True, verbose_name='Message')),
            ],
        ),
    ]
