# Generated by Django 2.2.2 on 2019-08-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('4', 'Thursday'), ('1', 'Monday'), ('3', 'Wednesday'), ('6', 'Saturday'), ('2', 'Tuesday'), ('5', 'Friday'), ('7', 'Sunday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
