# Generated by Django 2.2.4 on 2019-09-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('5', 'Friday'), ('7', 'Sunday'), ('1', 'Monday'), ('6', 'Saturday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('2', 'Tuesday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
