# Generated by Django 2.2.4 on 2019-09-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20190910_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('1', 'Monday'), ('7', 'Sunday'), ('4', 'Thursday'), ('3', 'Wednesday'), ('5', 'Friday'), ('6', 'Saturday'), ('2', 'Tuesday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
