# Generated by Django 2.2.2 on 2019-08-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20190824_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('1', 'Monday'), ('6', 'Saturday'), ('4', 'Thursday'), ('3', 'Wednesday'), ('7', 'Sunday'), ('5', 'Friday'), ('2', 'Tuesday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
