# Generated by Django 2.2.4 on 2019-09-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20190910_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('3', 'Wednesday'), ('2', 'Tuesday'), ('6', 'Saturday'), ('1', 'Monday'), ('4', 'Thursday'), ('7', 'Sunday'), ('5', 'Friday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
