# Generated by Django 2.2.2 on 2019-08-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20190824_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('7', 'Sunday'), ('2', 'Tuesday'), ('1', 'Monday'), ('4', 'Thursday'), ('3', 'Wednesday'), ('6', 'Saturday'), ('5', 'Friday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
