# Generated by Django 2.2.2 on 2019-09-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20190910_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('5', 'Friday'), ('6', 'Saturday'), ('4', 'Thursday'), ('1', 'Monday'), ('7', 'Sunday'), ('3', 'Wednesday'), ('2', 'Tuesday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
