# Generated by Django 2.2.2 on 2019-08-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20190829_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('7', 'Sunday'), ('3', 'Wednesday'), ('6', 'Saturday'), ('2', 'Tuesday'), ('5', 'Friday'), ('4', 'Thursday'), ('1', 'Monday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
