# Generated by Django 2.2.2 on 2019-09-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20190916_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('3', 'Wednesday'), ('1', 'Monday'), ('6', 'Saturday'), ('7', 'Sunday'), ('5', 'Friday'), ('4', 'Thursday'), ('2', 'Tuesday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
