# Generated by Django 2.2.4 on 2019-08-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20190829_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('7', 'Sunday'), ('5', 'Friday'), ('1', 'Monday'), ('3', 'Wednesday'), ('6', 'Saturday'), ('2', 'Tuesday'), ('4', 'Thursday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
