# Generated by Django 2.2.4 on 2019-08-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_auto_20190829_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('3', 'Wednesday'), ('2', 'Tuesday'), ('4', 'Thursday'), ('6', 'Saturday'), ('5', 'Friday'), ('7', 'Sunday'), ('1', 'Monday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
