# Generated by Django 2.2.4 on 2019-08-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_auto_20190829_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('1', 'Monday'), ('3', 'Wednesday'), ('2', 'Tuesday'), ('6', 'Saturday'), ('4', 'Thursday'), ('7', 'Sunday'), ('5', 'Friday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
