# Generated by Django 2.2.2 on 2019-08-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_auto_20190829_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'verbose_name': 'Date'},
        ),
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('6', 'Saturday'), ('5', 'Friday'), ('3', 'Wednesday'), ('2', 'Tuesday'), ('1', 'Monday'), ('4', 'Thursday'), ('7', 'Sunday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
