# Generated by Django 2.2.2 on 2019-08-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_auto_20190829_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'verbose_name': 'Date', 'verbose_name_plural': 'Dates'},
        ),
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('7', 'Sunday'), ('2', 'Tuesday'), ('1', 'Monday'), ('4', 'Thursday'), ('5', 'Friday'), ('3', 'Wednesday'), ('6', 'Saturday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
