# Generated by Django 2.2.2 on 2019-08-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_auto_20190829_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('6', 'Saturday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('5', 'Friday'), ('7', 'Sunday'), ('4', 'Thursday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
