# Generated by Django 2.2.2 on 2019-08-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_auto_20190829_2059'),
        ('timetable', '0010_auto_20190829_1858'),
    ]

    operations = [
    ]
