# Generated by Django 2.2.2 on 2019-08-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0016_merge_20190830_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('6', 'Saturday'), ('4', 'Thursday'), ('3', 'Wednesday'), ('7', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('5', 'Friday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
