# Generated by Django 2.2.2 on 2019-08-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0017_auto_20190831_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('1', 'Monday'), ('4', 'Thursday'), ('7', 'Sunday'), ('2', 'Tuesday'), ('6', 'Saturday'), ('5', 'Friday'), ('3', 'Wednesday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
