# Generated by Django 2.2.2 on 2019-08-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0018_auto_20190831_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('5', 'Friday'), ('1', 'Monday'), ('4', 'Thursday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
