# Generated by Django 2.2.4 on 2019-09-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0019_auto_20190831_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('2', 'Tuesday'), ('1', 'Monday'), ('3', 'Wednesday'), ('5', 'Friday'), ('7', 'Sunday'), ('6', 'Saturday'), ('4', 'Thursday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
