# Generated by Django 2.2.4 on 2019-09-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0020_auto_20190902_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('3', 'Wednesday'), ('2', 'Tuesday'), ('7', 'Sunday'), ('6', 'Saturday'), ('5', 'Friday'), ('4', 'Thursday'), ('1', 'Monday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
