# Generated by Django 2.2.2 on 2019-09-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0021_auto_20190903_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('5', 'Friday'), ('3', 'Wednesday'), ('1', 'Monday'), ('6', 'Saturday'), ('4', 'Thursday'), ('2', 'Tuesday'), ('7', 'Sunday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
