# Generated by Django 2.2.2 on 2019-09-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0022_auto_20190906_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('4', 'Thursday'), ('2', 'Tuesday'), ('5', 'Friday'), ('3', 'Wednesday'), ('1', 'Monday'), ('7', 'Sunday'), ('6', 'Saturday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
