# Generated by Django 2.2.2 on 2019-09-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0023_auto_20190906_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('1', 'Monday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('2', 'Tuesday'), ('6', 'Saturday'), ('7', 'Sunday'), ('5', 'Friday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
