# Generated by Django 2.2.2 on 2019-09-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0024_auto_20190906_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='weekday',
            field=models.CharField(choices=[('5', 'Friday'), ('4', 'Thursday'), ('2', 'Tuesday'), ('6', 'Saturday'), ('1', 'Monday'), ('7', 'Sunday'), ('3', 'Wednesday')], max_length=1, verbose_name='Day of the week'),
        ),
    ]
